name: Send Telegram Message Daily

on:
  schedule:
    - cron: '14 19 * * *' # Every day at 18:50 UTC
  workflow_dispatch:

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --filename=composer --install-dir=/usr/local/bin
        php -r "unlink('composer-setup.php');"
      
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    - name: Run script
      run: php bot.php
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
