name: Send Telegram Message Daily

on:
  schedule:
    - cron: '45 5 * * *' # Запуск в 09:00 по времени Таджикистана, Душанбе (GMT+5)

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
  
    - name: Run script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: php bot.php

    - name: Notify success
      if: success()
      run: echo "The Telegram bot script has been executed successfully."

    - name: Notify failure
      if: failure()
      run: echo "There was an error executing the Telegram bot script."
