name: Send Telegram Message Daily

on:
  schedule:
    - cron: '10 19 * * *' # Каждый день в 18:50 UTC
  workflow_dispatch:

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==13.7 python-dotenv urllib3

    - name: Run script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python bot.py
